name: "build & deploy to production server"

on:
  push:
    branches:
      - main

jobs:
  deploy-on-production-server:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:22.04
      options: --privileged
    steps:
      - name: install packages
        run: |
          apt-get update --allow-releaseinfo-change
          apt-get install openssh-client -y

      - name: setup openSSH config
        if: ${{ success() }}
        run: |
          cd ~
          mkdir .ssh
          cd .ssh/
          echo "${{secrets.PROD_SSH_PEM}}" > PROD_SSH.pem
          chmod 400 PROD_SSH.pem

      - name: dot env creation
        if: ${{ success() }}
        run: |
          cd ~
          mkdir dotenv
          cd dotenv/
          mkdir reptile_shop_web
          cd reptile_shop_web/
          echo '${{secrets.DOT_ENV_WEB}}' > .env.frontend
          ls -al
      - name: checkout
        uses: actions/checkout@v3

      - name: scp dot env files
        if: ${{ success() }}
        run: |
          scp -r -p -o StrictHostKeyChecking=accept-new -i ~/.ssh/PROD_SSH.pem ubuntu@162.19.67.240 ~/dotenv ubuntu@162.19.67.240:~ || echo

      - name: scp bash script
        if: ${{ success() }}
        run: |
          scp -r -p -o StrictHostKeyChecking=accept-new -i ~/.ssh/PROD_SSH.pem ubuntu@162.19.67.240 .github/workflows/deploy.reptiles_shop_web.sh ubuntu@162.19.67.240:~ || echo

      - name: connect SSH & run deploy script
        if: ${{ success() }}
        run: |
          ssh -o StrictHostKeyChecking=accept-new -i ~/.ssh/PROD_SSH.pem ubuntu@162.19.67.240 /bin/bash -s << EOT
          chmod +x ~/deploy.reptiles_shop_web.sh
          ~/deploy.reptiles_shop_web.sh > ~/logs/reptile_shop_web/log.deploy.$( date +"%s") 2>&1 & disown
          exit
          EOT